### ISSUE TITLE
Trouble displaying static front page and blog post page

### ISSUE THREAD

**Issue by ghost** [taniarascia/oblate#1]
Hi Tania

Firstly thank you for creating your wonderful website I've learned a lot browsing through your articles. I particularly liked your Oblate theme so I decided to have a play about with it. However I'm having a bit of an issue, I'm sure it's just me being stupid so thought id as your advice. 

Basically, with the default "display latest posts" set the static homepage shows up as it should but I can't get the blog page to work under this setting. I tried to change the settings from "show latest posts" to a custom front page and blog page. I can set the blog page to a page I created named blog but I can't find a way to display the static front page as the homepage. Any ideas? 

Kind Regards

Jus
@sassigeek

**Comment by ghost** [comment]
I think I've done it, maybe not the correct way but it works. 

I created a page called blog and assigned it as the blog page under settings > reading. So /blog now shows all the blog posts

I then created a page called home and assigned the front-page.php to the newly created /home page and then set this to the front page under settings > reading. So it works now, not sure if this is the correct way but it's definitely working.

**Comment by taniarascia** [comment]
Yep, that's the right way! Or at least how I do it. Sorry I missed this.
