### ISSUE TITLE
database export as starter kit

### ISSUE THREAD

**Issue by mircobabini** [taniarascia/oblate#2]
Hi Tania, first of all: very very nice theme.
I'd love to use it as the parent theme on my personal blog as well and support the development providing you pull requests every time I produce something cool on it. But, to do so, it would be great:
1. that the style.css had a new (minor) version any time the theme changes
2. to have an export of the current database already filled with some contents

Hope you're doin' well,
M

**Comment by taniarascia** [comment]
To be honest, I think the best idea would be for me to make a new theme focusing on simplicity for others to use for their own personal blogs. This one has too many references to me, and me-specific things, and I haven't even integrated the menu into WordPress out of laziness. You've given me an idea, so I'll work on it and make a new open source theme.

**Comment by mircobabini** [comment]
Magnificence brings more magnificence! Let me know something so, can't wait for it!
I renew my availability to contribute in the future.

Cheers,
