### ISSUE TITLE
"Stylesheet is missing."

### ISSUE THREAD

**Issue by emresaracoglu** [taniarascia/oblate#3]
Hello,

I am getting this error, how can I fix?

![fireshot screen capture 015 - manage themes emre saracoglu technology blog wordpress - tech_emresaracoglu_com_wp-admin_themes_php](https://cloud.githubusercontent.com/assets/297968/25903014/e7699d04-35a3-11e7-8a15-ba2162ec6e49.png)

Thank you

**Comment by taniarascia** [comment]
Hi,

I'm sorry, I'm not sure why you're getting that error. However, this theme is not publicly supported. It is simply my website's source code, available for your inspiration.

**Comment by emresaracoglu** [comment]
I understand, thank you for answer.
